
required = [ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway", "github.com/square/goprotowrap" ]

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.2.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/square/goprotowrap"
  branch = "master"
